apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx:latest
        name: web-container
        ports:
        - containerPort: 8080
      - image: mysql:latest
        name: db-container
        ports:
        - containerPort: 3306
      - image: nginx:stable
        name: prod-web-container
        ports:
        - containerPort: 80
      - image: mysql:8.0
        name: prod-db-container
        ports:
        - containerPort: 3306
